import { AuditReport } from "./linker";

export function formatAuditReportMarkdown(report: AuditReport): string {
  const lines: string[] = [
    "# Vault Linker audit",
    "",
    `- Pending links (would add): **${String(report.pendingLinks)}** in **${String(report.pendingFiles)}** notes`,
    `- Broken wikilinks: **${String(report.brokenLinks.length)}**`,
    `- Notes with zero incoming links: **${String(report.zeroBacklinkNotes.length)}**`,
    "",
  ];

  if (report.brokenLinks.length > 0) {
    lines.push("## Broken wikilinks", "");
    for (const broken of report.brokenLinks) {
      lines.push(
        `- \`${broken.filePath}:${String(broken.line)}\` ${broken.wikilink} → missing \`${broken.target}\``
      );
    }
    lines.push("");
  }

  if (report.zeroBacklinkNotes.length > 0) {
    lines.push("## Zero incoming links", "");
    for (const title of report.zeroBacklinkNotes.slice(0, 100)) {
      lines.push(`- ${title}`);
    }
    if (report.zeroBacklinkNotes.length > 100) {
      lines.push(`- … and ${String(report.zeroBacklinkNotes.length - 100)} more`);
    }
    lines.push("");
  }

  if (report.topLinkedTitles.length > 0) {
    lines.push("## Most linked titles", "");
    for (const entry of report.topLinkedTitles) {
      lines.push(`- ${entry.title} (${String(entry.count)})`);
    }
    lines.push("");
  }

  lines.push("_Generated by Vault Linker_");
  return lines.join("\n");
}
